### 4.11.2　自定义异常

事实上，Kotlin标准库提供的异常类型无法处理所有可能的异常情况，此时可以通过自定义异常来解决程序中出现的特定问题。如果想要使用自定义异常，就必须继承现有的异常类，然后根据具体情况进行处理。代码如下。

```python
fun main(args: Array<String>) {
  var b: String? = null
  try {
    b?.length ?: throw MyExcepttion("b不能为空")
  } catch (ex: MyExcepttion) {
    println("ex: ${ex.message}")
  } catch (npe: NullPointerException) {
    println("npe: ${npe.message}")
  } finally {
    println("finally")
  }
}
public class MyExcepttion(override val message: String) : Throwable(){
    //异常情况处理
}
```

