[toc]

### 1. 错误代码

许多系统调用和函数都会因为各种各样的原因而失败。它们会在失败时设置外部变量 `errno` 的值来指明失败的原因。许多不同的函数库都把这个变量用作报告错误的标准方法。值得注意的是，程序必须在函数报告出错之后立刻检查 `errno` 变量，因为它可能被下一个函数调用所覆盖，即使下一个函数自身并没有出错，也可能会覆盖这个变量。

错误代码的取值和含义都定义在头文件 `errno.h` 里，如下所示：

+ `EPERM`：操作不允许。
+ `ENOENT`：文件或目录不存在。
+ `EINTR`：系统调用被中断。
+ `EIO`：I/O 错误。
+ `EBUSY`：设备或资源忙。
+ `EEXIST`：文件存在。
+ `EINVAL`：无效参数。
+ `EMFILE`：打开的文件过多。
+ `ENODEV`：设备不存在。
+ `EISDIR`：是一个目录。
+ `ENOTDIR`：不是一个目录。

有两个非常有用的函数可以用来报告出现的错误，它们是 `strerror` 和 `perror`。

### 2. strerror 函数

`strerror` 函数把错误代码映射为一个字符串，该字符串对发生的错误类型进行说明。该函数原型如下：

```c
#include <string.h>

char *strerror(int errnum);
```

### 3. perror 函数

`perror` 函数也把 `errno` 变量中报告的当前错误映射到一个字符串，并把它输出到标准错误输出流。该字符串的签名先加上字符串 s（如果不为空）中给出的信息，再加上一个冒号和一个空格。该函数原型如下：

```c
#include <stdio.h>

void perror(const char *s);
```

### 4. 示例代码

```c
#include<fcntl.h>
#include<unistd.h>
#include<sys/types.h>
#include<sys/stat.h>
#include<errno.h>
#include<stdio.h>
#include<string.h>

int main()
{
	const char *file_name = "test.py";
	const char *err_msg_pref = "Error";
	int fd;
	int error;
	char *err_msg;
	char msg[1024];
	
	fd = open(file_name, O_CREAT|O_EXCL|O_WRONLY|O_APPEND, S_IRUSR|S_IWUSR|S_IRGRP|S_IWGRP|S_IROTH);
	if (fd == -1) {
		error = errno;
		perror(err_msg_pref);
		err_msg = strerror(error);
		sprintf(msg, "Error message: %s\n", err_msg);
		write(2, msg, strlen(msg));
	}
	close(fd);
	return 0;
}
```

