错误处理允许您确定失败的根本原因，并在必要时将错误传播到程序的另一部分.当函数遇到错误条件时，它*会抛出*错误。然后该函数的调用者可以*捕获*错误并做出适当的响应。

```swift
func canThrowAnError() throws {
    // this function may or may not throw an error
}
```

函数表明它可以通过在其声明中包含 `throws` 关键字来抛出错误。当您调用可能引发错误的函数时，您将 `try` 关键字添加到表达式之前。

Swift 会自动将错误传播到当前范围之外，直到它们被子句处理为止 `catch`。

```swift
do {
    try canThrowAnError()
    // no error was thrown
} catch {
    // an error was thrown
}
```

`do` 语句创建一个新的包含范围，它允许将错误传播到一个或多个 `catch` 子句。

以下是如何使用错误处理来响应不同错误条件的示例：

```swift
func makeASandwich() throws {
    // ...
}

do {
    try makeASandwich()
    eatASandwich()
} catch SandwichError.outOfCleanDishes {
    washDishes()
} catch SandwichError.missingIngredients(let ingredients) {
    buyGroceries(ingredients)
}
```

[错误处理](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/errorhandling)中更详细地介绍了抛出、捕获和传播错误。